# Generated by Django 4.2.6 on 2023-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, default='example@email.com', max_length=200, unique=True)),
                ('bougt_items', models.JSONField(blank=True, default=list, verbose_name='Bought Items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
