# Generated by Django 4.2.6 on 2023-10-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='quantity',
        ),
    ]
