# Generated by Django 4.2.6 on 2023-10-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('cart', '0004_remove_cart_quantity_cart_item_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart_item',
            unique_together={('cart', 'item')},
        ),
    ]
